---
# tasks file for roles/app
- name: Run backend API
  community.docker.docker_container:
    name: backend
    image: faridlp/simple-api:1.0
    state: started
    restart_policy: always
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd