name: Deploy to production

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_takima
          chmod 600 ~/.ssh/id_rsa

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H farid-camed.aboubakari.takima.school >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: |
          cd ansible
          ansible-playbook -i inventories/setup.yml playbook.yml