name: Docker Build and Push
on:
  #to begin you want to launch this job in main and develop
  workflow_run: 
    workflows: ["Sonar Analysis"]
    types:
      - completed
    branches: 
    - main



jobs:    
    # define job to build and publish docker image
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Log in to Docker Hub if building on main branch
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          # relative path to the place where source code with Dockerfile is located
          context: backend-api/demo
          # Note: tags has to be all lower-case
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest
          push: true

      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: database
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-db:latest
          push: true

      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: http-server
          tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-httpd:latest
          push: true

